### ISSUE TITLE
Error:  uninitialized constant

### ISSUE THREAD

**Issue by keirwilliams-old** [ashmaroli/jekyll-locale#14]
When I try to serve my site with `bundle exec jekyll serve` I get this:

    Liquid Exception: uninitialized constant Jekyll::Locale::PageDrop Did you mean? Jekyll::PageReader in /_layouts/default.html
    jekyll 3.8.3 | Error:  uninitialized constant Jekyll::Locale::PageDrop
    Did you mean?  Jekyll::PageReader

Not sure if it's something I've done wrong or not.

**Comment by ashmaroli** [comment]
Thank you for reporting this @keirwilliams 
Can you try and check if this issue is reproducible with the `master` branch of this repo?
```ruby
gem "jekyll-locale", git: "https://github.com/ashmaroli/jekyll-locale.git", branch: "master"
```

**Comment by keirwilliams-old** [comment]
I no longer have the issue when using the `master` branch.

**Comment by ashmaroli** [comment]
Glad to know that @keirwilliams 
Therefore, I'll consider this issue to have been resolved.
Thank you.
